// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: etcdserverpb/etcdserver.proto

package etcdserverpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_etcdserverpb_etcdserver_proto protoreflect.FileDescriptor

const file_etcdserverpb_etcdserver_proto_rawDesc = "" +
	"\n" +
	"\x1detcdserverpb/etcdserver.proto\x12\fetcdserverpbB\xa4\x01\n" +
	"\x10com.etcdserverpbB\x0fEtcdserverProtoP\x01Z/go.withmatt.com/connect-etcd/types/etcdserverpb\xa2\x02\x03EXX\xaa\x02\fEtcdserverpb\xca\x02\fEtcdserverpb\xe2\x02\x18Etcdserverpb\\GPBMetadata\xea\x02\fEtcdserverpbb\x06proto3"

var file_etcdserverpb_etcdserver_proto_goTypes = []any{}
var file_etcdserverpb_etcdserver_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_etcdserverpb_etcdserver_proto_init() }
func file_etcdserverpb_etcdserver_proto_init() {
	if File_etcdserverpb_etcdserver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_etcdserverpb_etcdserver_proto_rawDesc), len(file_etcdserverpb_etcdserver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_etcdserverpb_etcdserver_proto_goTypes,
		DependencyIndexes: file_etcdserverpb_etcdserver_proto_depIdxs,
	}.Build()
	File_etcdserverpb_etcdserver_proto = out.File
	file_etcdserverpb_etcdserver_proto_goTypes = nil
	file_etcdserverpb_etcdserver_proto_depIdxs = nil
}
